name: Docker Build -> Push -> Deploy 

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:  
    - name: Setup Java
      uses: actions/checkout@v4 
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '25'

    - name: Build Jar
      run: |
        chmod +x ./mvnw
        ./mvnw clean package -DskipTests

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker Image
      run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/spring-boot-ci-demo:latest .

    - name: Push Image to Docker Hub
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/spring-boot-ci-demo:latest

    - name: SSH and Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{secrets.EC2_HOST}}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker stop spring-demo || true
          delete rm spring-demo || true
          docker pull ${{secrets.DOCKERHUB_USERNAME}}/spring-boot-ci-demo:latest
          docker run -d --name spring-demo -p 8081:8081 ${{secrets.DOCKER_USERNAME}}/spring-boot-ci-demo:latest




        
